# Generated by Django 6.0.2 on 2026-03-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('car_for_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('parts_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('salesperson_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealership.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('service_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_ticket_number', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_returned_to_customer', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMechanic',
            fields=[
                ('servicemechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.service')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsed',
            fields=[
                ('parts_used_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_used', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.parts')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.serviceticket')),
            ],
        ),
    ]
